title: Drawpile
description: Collaborative Drawing
domain: drawpile.github.io
baseurl: "/"
url: "https://drawpile.github.io"
github_username: drawpile
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
